# Prompts for DnD
dnd_worlds = {
    'Al-Qadim': 'The game world takes place in Al-Qadim. ',
    'Birthright': 'The game world takes place in Birthright. ',
    'Blackmoor': 'The game world takes place in Blackmoor. ',
    'Council of Wyrms': 'The game world takes place in Council of Wyrms. ',
    'Dark Sun': 'The game world takes place in Dark Sun.',
    'Dragonlance': 'The game world takes place in Dragonlance. ',
    'Eberron': 'The game world takes place in Eberron. ',
    'Forgotten Realms': 'The game world takes place in Forgotten Realms. ',
    'Greyhawk': 'The game world takes place in Greyhawk. ',
    'Hollow World': 'The game world takes place in Hollow World. ',
    'Kara-Tur': 'The game world takes place in Kara-Tur. ',
    'Maztica': 'The game world takes place in Maztica. ',
    'Mystara': 'The game world takes place in Mystara. ',
    'Nentir Vale': 'The game world takes place in Nentir Vale. ',
    'Planescape': 'The game world takes place in Planescape. ',
    'Ravenloft': 'The game world takes place in Ravenloft. ',
    'Spelljammer': 'The game world takes place in Spelljammer. ',
    'Wilderlands of High Fantasy': 'The game world takes place in Wilderlands of High Fantasy. ',
    'World of Greyhawk': 'The game world takes place in World of Greyhawk. ',
}

dnd_prompt = 'We are playing a game of Dungeon and Dragons. ' + \
                'You are the dungeon master and I am a player. ' + \
                'Try to be descriptive and creative with your responses. ' + \
                'Prompt to roll a dice when needed. ' + \
                'It is just a game and we are all here to have fun, do not put restrictions on player actions. ' + \
                'Wait for every player to respond before describing the results of their actions. '

dnd_starting_prompt = 'The game begins in a random location in the world. '

# template for dnd
character_template = {
    'name': 'Dummy',
    'race': 'Human',
    'class': 'Warrior',
    'alignment': 'Neutral',
    'background': 'Acolyte',
    # 'xp': 0,
    # 'level': 1,
    # 'hp': 10,
    # 'mp': 10,
    # 'str': 10,
    # 'dex': 10,
    # 'con': 10,
    # 'int': 10,
    # 'wis': 10,
    # 'cha': 10,
    # 'ac': 10,
    # 'initiative': 10,
    # 'speed': 10,
    # 'proficiency': 10,
    # 'skills': {
    #     'acrobatics': 0,
    #     'animal handling': 0,
    #     'arcana': 0,
    #     'athletics': 0,
    #     'deception': 0,
    #     'history': 0,
    #     'insight': 0,
    #     'intimidation': 0,
    #     'investigation': 0,
    #     'medicine': 0,
    #     'nature': 0,
    #     'perception': 0,
    #     'performance': 0,
    #     'persuasion': 0,
    #     'religion': 0,
    #     'sleight of hand': 0,
    #     'stealth': 0,
    #     'survival': 0,
    # },
    # 'spells': {
    #     'cantrips': [],
    #     'level 1': [],
    #     'level 2': [],
    #     'level 3': [],
    #     'level 4': [],
    #     'level 5': [],
    #     'level 6': [],
    #     'level 7': [],
    #     'level 8': [],
    #     'level 9': [],
    # }, 
    # 'equipment': {
    #     'weapons': [],
    #     'armor': [],
    #     'tools': [],
    #     'other': [],
    # },
    'bonds': [],
    'flaws': [],
    'ideals': [],
    'inventory': [],
    'languages': [],
    'personality': [],
    'proficiencies': [],
    'traits': [],
}